### ISSUE TITLE
针对双实体多关系怎么办？

### ISSUE THREAD

**Issue by eclipse-du** [bojone/kg-2019-baseline#6]
尊敬的苏神您好，
1.如果两个实体存在多种关系（比如NYT10这种数据集），那现在这种双标注是不是会崩，举例来说“诸葛亮和姜维的关系，既是老师也是朋友。”
2.拜读了您之前提出的“半指针-半标注“，有一点困惑，如果说半标注是指把答案的begin和end分开标注，半指针怎么理解，原先阅读理解不也是分开预测开始和结束么，是不是分开预测都可以叫半指针？
谢谢

**Comment by bojone** [comment]
请看 https://kexue.fm/archives/6671 和 https://github.com/bojone/kg-2019

本baseline不再更新
